#!/bin/bash


sudo apt-get update
sudo apt install apache2 -y
sudo systemctl status apache2
mkdir /var/www/html/order/
echo "<h1>Welcome to Order Service</h1>">/var/www/html/order/index.html
systemctl start apache2
